# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epingpong.proto\x12\x13\x63om.jmp.task1.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"P\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x30\n\x0crequest_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"R\n\x0cPongResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x31\n\rresponse_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp2\xc4\x01\n\x0fPingPongService\x12R\n\x0bgetResponse\x12 .com.jmp.task1.proto.PingRequest\x1a!.com.jmp.task1.proto.PongResponse\x12]\n\x14getMultipleResponses\x12 .com.jmp.task1.proto.PingRequest\x1a!.com.jmp.task1.proto.PongResponse0\x01\x42\x17\n\x13\x63om.jmp.task1.protoP\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pingpong_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\023com.jmp.task1.protoP\001'
  _PINGREQUEST._serialized_start=72
  _PINGREQUEST._serialized_end=152
  _PONGRESPONSE._serialized_start=154
  _PONGRESPONSE._serialized_end=236
  _PINGPONGSERVICE._serialized_start=239
  _PINGPONGSERVICE._serialized_end=435
# @@protoc_insertion_point(module_scope)
