# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pingpong_pb2 as pingpong__pb2


class PingPongServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getResponse = channel.unary_unary(
                '/com.jmp.task1.proto.PingPongService/getResponse',
                request_serializer=pingpong__pb2.PingRequest.SerializeToString,
                response_deserializer=pingpong__pb2.PongResponse.FromString,
                )
        self.getMultipleResponses = channel.unary_stream(
                '/com.jmp.task1.proto.PingPongService/getMultipleResponses',
                request_serializer=pingpong__pb2.PingRequest.SerializeToString,
                response_deserializer=pingpong__pb2.PongResponse.FromString,
                )


class PingPongServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMultipleResponses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PingPongServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.getResponse,
                    request_deserializer=pingpong__pb2.PingRequest.FromString,
                    response_serializer=pingpong__pb2.PongResponse.SerializeToString,
            ),
            'getMultipleResponses': grpc.unary_stream_rpc_method_handler(
                    servicer.getMultipleResponses,
                    request_deserializer=pingpong__pb2.PingRequest.FromString,
                    response_serializer=pingpong__pb2.PongResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.jmp.task1.proto.PingPongService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PingPongService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.jmp.task1.proto.PingPongService/getResponse',
            pingpong__pb2.PingRequest.SerializeToString,
            pingpong__pb2.PongResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMultipleResponses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/com.jmp.task1.proto.PingPongService/getMultipleResponses',
            pingpong__pb2.PingRequest.SerializeToString,
            pingpong__pb2.PongResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
